version: 2

project_name: amnezia-client-image

# No Go builds — release management only (Docker image built via buildx)
builds:
  - skip: true

changelog:
  use: github
  groups:
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Documentation"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Other"
      order: 999
  filters:
    exclude:
      - "^chore:"
      - "^ci:"
      - "^test:"

release:
  github:
    owner: "Windemiatrix"
    name: "amnezia-client-image"
  prerelease: auto
  name_template: "{{ .Tag }}"
